### ISSUE TITLE
Why the cache plugin use ncache as Preferred cache?

### ISSUE THREAD

**Issue by IIvyPy** [miekg/coredns#4869]
I think that ncache seems an useless response. When there is a query name which not only has ncache, but also has pcache, the code above will choose ncache.  Is this illogical？

func (c *Cache) get(now time.Time, state request.Request, server string, geoView uint16) (*item, bool) {
	k := hash(state.Name(), state.QType(), geoView)

	if i, ok := c.ncache.Get(k); ok && i.(*item).ttl(now) > 0 {
		cacheHits.WithLabelValues(server, Denial).Inc()
		return i.(*item), true
	}

	if i, ok := c.pcache.Get(k); ok && i.(*item).ttl(now) > 0 {
		cacheHits.WithLabelValues(server, Success).Inc()
		return i.(*item), true
	}
	cacheMisses.WithLabelValues(server).Inc()
	return nil, false
}

**Comment by IIvyPy** [comment]
question 2: why we have ncache in CoreDNS?

**Comment by chrisohaver** [comment]
> Why the cache plugin use ncache as Preferred cache?

Negative cache _is_ checked first, which I suppose gives it slight performance edge vs positive cache hits.  But it doesn't suffer from the problem you describe, because the "in both caches" scenario doesn't happen.

With normal default cache operation you won't have an entry in both caches for the same name.  We only cache a response when we miss cache. So for example, we'd only write to `ncache` if there are no unexpired entries in `ncache` and `pcache`.

This is different when "prefetching" is enabled. With prefetching we will refresh unexpired answers in the cache.  In that case if we get a positive answer, we remove the negative cache entry so it doesn't eclipse the positive cache.

**Comment by IIvyPy** [comment]
> > Why the cache plugin use ncache as Preferred cache?
> 
> Negative cache _is_ checked first, which I suppose gives it slight performance edge vs positive cache hits. But it doesn't suffer from the problem you describe, because the "in both caches" scenario doesn't happen.
> 
> With normal default cache operation you won't have an entry in both caches for the same name. We only cache a response when we miss cache. So for example, we'd only write to `ncache` if there are no unexpired entries in `ncache` and `pcache`.
> 
> This is different when "prefetching" is enabled. With prefetching we will refresh unexpired answers in the cache. In that case if we get a positive answer, we remove the negative cache entry so it doesn't eclipse the positive cache.

what makes me confused is that the "in both caches" scenario doesn't happen, why we use both `ncache` and `pcache`? If we just use one single cache, what would happen?

**Comment by chrisohaver** [comment]
> why we use both ncache and pcache?

I suspect that negative cache was added as a separate instance of a cache because it was a simple way to add negative caching, while allowing positive and negative cache behavior to be configured independently.
