### ISSUE TITLE
 after several miniutes, the changes I made to the coredns configmap lost.

### ISSUE THREAD

**Issue by abnormall** [miekg/coredns#4918]
**My Goal:**
I want to add a DNS entry into coredns configuration.  
ex.      app1-dapr.default.svc.cluster.local -> 10.10.0.1 

The service named app1-dapr does not exsit in the AKS. 

**My environment:** 
In AKS

**Problem:**
I add few lines in the coreos ConfigMap with the command _**_kubectl edit cm coredns -n kube-system_**_ , and the final ConfigMap is listed as below:

```
apiVersion: v1
data:
  Corefile: |
    .:53 {
        errors
        ready
        health
        hosts /etc/coredns/customdomains.db cluster.local {
          fallthrough
        }
        kubernetes cluster.local in-addr.arpa ip6.arpa {
          pods insecure
          fallthrough in-addr.arpa ip6.arpa
        }
        prometheus :9153
        forward . /etc/resolv.conf
        cache 30
        loop
        reload
        loadbalance
        import custom/*.override
    }
    import custom/*.server
    customdomains.db: |
    10.10.0.1 app1-dapr.default.svc.cluster.local
    import custom/*.server
```
I added these two things:
```        
hosts /etc/coredns/customdomains.db cluster.local {
          fallthrough
        }
```
```   
 customdomains.db: |
    <ingress-ip> app1-dapr.default.svc.cluster.local
```
I also edit the config-volume for the CoreDNS pod template by the command **kubectl edit -n kube-system deployment coredns**

```volumes:
        - name: config-volume
          configMap:
            name: coredns
            items:
            - key: Corefile
              path: Corefile
            - key: customdomains.db
              path: customdomains.db
```
It can work for a few miniutes. The successful result is the coredns can map the app1-dapr.default.svc.cluster.local to 10.10.0.1. 
But after several miniutes, the changes I made to the coredns configmap lost and it will return NXDOMAIN.

**Comment by chrisohaver** [comment]
This is probably better asked to AKS support.  This behavior is due to AKS specific restrictions enforced by their service, not something inherent to CoreDNS in other K8s environments. That said...

My understanding is that AKS doesn't allow you to modify the Corefile data in the Configmap, but they added two `import` directives: one for adding new plugins into the root zone server block(`import custom/*.override `), and another for adding new server blocks (`import custom/*.server `).  So, instead of adding the Corefile data directly, try to add/mount new data to `custom/*.override` e.g. `custom/hosts.override`, and add the host plugin to that instead.

**Comment by abnormall** [comment]
@chrisohaver yes, you are right. Thanks for your help. I have solved the problem.
