### ISSUE TITLE
Why does having search in a host's `/etc/resolv.conf` break DNS/CoreDNS so commonly? 

### ISSUE THREAD

**Issue by anthr76** [miekg/coredns#4923]
**What happened**:

Have a `/etc/resolv.conf` on host like:

```
cat /etc/resolv.conf
search scr1.rabbito.tech
nameserver 192.168.8.1
```

Have a `/etc/resolv.conf` on pod like:

```
cat /etc/resolv.conf
search default.svc.cluster.local svc.cluster.local cluster.local scr1.rabbito.tech
nameserver 10.96.0.10
options ndots:5
```

**What you expected to happen**:

A DNS query not to look like this 

```
[root@debug-pod-worker-3 toolbox]# nslookup google.com
Server:         10.96.0.10
Address:        10.96.0.10#53

*** Can't find google.com.scr1.rabbito.tech: No answer
```

Instead:

```
[root@debug-pod-worker-2 toolbox]# nslookup google.com
Server:         10.96.0.10
Address:        10.96.0.10#53

Non-authoritative answer:
Name:   google.com
Address: 172.217.1.206
Name:   google.com
Address: 2607:f8b0:4004:801::200e
```

**How to reproduce it (as minimally and precisely as possible)**:
?
For me always, and some peers I've chatted with

**Anything else we need to know?**:

**Environment**:

- the version of CoreDNS: v1.8.6
- Corefile: https://github.com/anthr76/infra/blob/main/gitops/base/kube-system/coredns/config-map.yaml
- logs, if applicable:
- OS (e.g: `cat /etc/os-release`): Talos
- Others:

Not sure if it's just best practice to avoid having a search in your host's `/etc/resolv.conf` but usually in some way or another it ends up wreaking havoc. In Talos OS case it **always** provisions the search for you (https://github.com/talos-systems/talos/blob/master/internal/app/machined/pkg/controllers/network/etcfile.go) which before I go and report from them this is likely a bad idea I figured I would check here first..

**Comment by chrisohaver** [comment]
The resolv.conf created for Pods is not controlled by CoreDNS. It is controlled by kubelet in Kubernetes. Also, the decision of when to stop searching the search list and settle on an answer is made by the worker Pod, not CoreDNS.

If nslookup’s “no answer” == NOERROR + zero Answers (aka NODATA), that would prompt the resolver on debug-pod-worker-3 to stop searching and display that answer, instead of trying bare “google.com.” next. If so, the server 192.168.8.1:53 should instead be returning NXDOMAIN, which would prompt the resolver to try the next domain or  bare search name if no search domains remain.
