### ISSUE TITLE
plugin/kubernetes: add pod annotations to available metadata

### ISSUE THREAD

**Issue by cbroglie** [miekg/coredns#5062]
**What would you like to be added**:

I would like to make pod annotations available to other plugins via metadata.

**Why is this needed**:

My use case is to leverage pod annotation values in policy decisions made by the [firewall](https://github.com/coredns/policy) plugin. In particular, I'd like to use it as part of chaos testing, allowing pods to opt into varying levels of chaos via annotation. This is building on ideas from https://github.com/coredns/policy/pull/32.

**Implementation**:

I'm happy to contribute a PR and tests for this, it should largely just consist of the (untested) diff below. But it contains a change to the `object.Pod` struct, which warns:
```go
type Pod struct {
	// Don't add new fields to this struct without talking to the CoreDNS maintainers.
	// ...
}
```
Would this change be acceptable? The downside would be increased memory allocations.

```diff
diff --git a/plugin/kubernetes/metadata.go b/plugin/kubernetes/metadata.go
index 36e2f9a0..1662890a 100644
--- a/plugin/kubernetes/metadata.go
+++ b/plugin/kubernetes/metadata.go
@@ -19,6 +19,12 @@ func (k *Kubernetes) Metadata(ctx context.Context, state request.Request) contex
 		metadata.SetValueFunc(ctx, "kubernetes/client-pod-name", func() string {
 			return pod.Name
 		})
+
+		for key, value := range pod.Annotations {
+			metadata.SetValueFunc(ctx, "kubernetes/client-pod-annotation-"+key, func() string {
+				return value
+			})
+		}
 	}
 
 	zone := plugin.Zones(k.Zones).Matches(state.Name())
diff --git a/plugin/kubernetes/object/pod.go b/plugin/kubernetes/object/pod.go
index 9b9d5641..56f4e902 100644
--- a/plugin/kubernetes/object/pod.go
+++ b/plugin/kubernetes/object/pod.go
@@ -16,6 +16,7 @@ type Pod struct {
 	PodIP       string
 	Name        string
 	Namespace   string
+	Annotations map[string]string
 
 	*Empty
 }
@@ -34,6 +35,13 @@ func ToPod(obj meta.Object) (meta.Object, error) {
 		Namespace: apiPod.GetNamespace(),
 		Name:      apiPod.GetName(),
 	}
+	if apiPod.Annotations != nil {
+		pod.Annotations = make(map[string]string, len(apiPod.Annotations))
+		for key, val := range apiPod.Annotations {
+			pod.Annotations[key] = val
+		}
+	}
+
 	t := apiPod.ObjectMeta.DeletionTimestamp
 	if t != nil && !(*t).Time.IsZero() {
 		// if the pod is in the process of termination, return an error so it can be ignored
@@ -56,6 +64,12 @@ func (p *Pod) DeepCopyObject() runtime.Object {
 		Namespace: p.Namespace,
 		Name:      p.Name,
 	}
+	if p.Annotations != nil {
+		p1.Annotations = make(map[string]string, len(p.Annotations))
+		for key, val := range p.Annotations {
+			p1.Annotations[key] = val
+		}
+	}
 	return p1
 }
 
@@ -76,3 +90,9 @@ func (p *Pod) GetResourceVersion() string { return p.Version }
 
 // SetResourceVersion implements the metav1.Object interface.
 func (p *Pod) SetResourceVersion(version string) {}
+
+// GetAnnotations implements the metav1.Object interface.
+func (p *Pod) GetAnnotations() map[string]string { return p.Annotations }
+
+// SetAnnotations implements the metav1.Object interface.
+func (p *Pod) SetAnnotations(annotations map[string]string) {}
```

**Comment by chrisohaver** [comment]
I think the use case is a bit narrow to justify the bump in memory usage for all `pods verified` users.

Pod monitoring is not required by the K8s service discovery spec, so this would only affect deployments with `pods verified`, which is not a default setting.  For those who do use `pods verified`, most of them will not be using annotations metadata.

We could add a new `pods` mode ... e.g. `pods annotated` that acts like `pods verified`, but also copies annotations into `object.Pod`.  Or if there is aversion to adding any config options/changes, copying annotations into `object.Pod` could be done only when the _metadata_ plugin is also enabled.

Another solution would be to implement this as external plugin that monitors Pods and and adds the metadata.  I recently wrote an external plugin that [monitors k8s nodes](https://github.com/infobloxopen/kubenodes), instead of extending the existing _kubernetes_ plugin.

**Comment by cbroglie** [comment]
>I think the use case is a bit narrow to justify the bump in memory usage for all pods verified users.
>We could add a new pods mode ... e.g. pods annotated that acts like pods verified, but also copies annotations into object.Pod

Yeah, I understand the reluctance for the narrow use case and putting it behind additional config option sounds fine. Either a new pods mode, or just another config option which is only used in `pods verified` mode.

>Or if there is aversion to adding any config options/changes, copying annotations into object.Pod could be done only when the metadata plugin is also enabled.

This would certainly work for our use case as well!

>Another solution would be to implement this as external plugin that monitors Pods and and adds the metadata.

The downside of this is an additional watch on all pods, right? I think we want to avoid that.

**Comment by chrisohaver** [comment]
> The downside of [an external plugin] is an additional watch on all pods, right? I think we want to avoid that.

Since Pods are not watched by default, it would only be additional if someone is using `pods verified` for some reason.

If you are using `pods verified` for the metadata it produces, that same metadata could be produced by the external plugin, and the _kubernetes_ plugin pod watch could be disabled.

**Comment by cbroglie** [comment]
We’re using verified for its pod ip guarantees, not just for metadata

**Comment by chrisohaver** [comment]
FWIW - I added pod annotation metadata to https://github.com/coredns/kubepods.

**Comment by johnbelamaric** [comment]
@chrisohaver is there a plan to transition from the current k8s plugin to kubeapi + others? It's definitely a nice refactor that can enable future use cases without complicating k8s plugin more. How much have you covered in other plugins, I haven't been following this...seems like we could move all the functionality to this refactor over time?

**Comment by chrisohaver** [comment]
> is there a plan to transition from the current k8s plugin to kubeapi + others? It's definitely a nice refactor that can enable future use cases without complicating k8s plugin more.

Thanks! No solid plan yet, but it's something that I have in mind to push for eventually if it proves to be practical.

> How much have you covered in other plugins, I haven't been following this...seems like we could move all the functionality to this refactor over time?

We could. None of the current DNS Based Service Discovery Spec is actually implemented yet. DNS names for Pods was completely removed from the spec in 2019.  

Currently implemented:

_kubepods_ - which implements the deprecated Pods behavior of the DNS Based Service Discovery Spec (verified and unverified). Also can use Pod names instead of IP addresses. 

_kubenodes_ - which adds DNS record for nodes.

I think would be nice if the _kubernetes_ plugin only implemented the requirements of Kubertnetes' DNS Based Service Discovery Spec, and anything extra implemented by a separate plugin.  However, this may not always be practical or clear cut.

**Comment by johnbelamaric** [comment]
> I think would be nice if the kubernetes plugin only implemented the requirements of Kubertnetes' DNS Based Service Discovery Spec, and anything extra implemented by a separate plugin. However, this may not always be practical or clear cut.

Makes sense. Not sure its possible for things that "tweak" the schema, like using pod names for endpoints. But for "extra" records it makes sense, and for things like `k8s_external` perhaps.

**Comment by chrisohaver** [comment]
> pod names for endpoints

Precisely what I had in mind as fuzzy and impractical to separate. Although, in that case the spec doesn’t prescribe what unique id to use, just that we have to use something unique.

**Comment by chrisohaver** [comment]
> The downside of this is an additional watch on all pods, right? I think we want to avoid that. 

_kubepods_ (https://github.com/coredns/kubepods) also implements the defunct deprecated `pod` subdomain of K8s [DNS Based Service Discovery Spec](https://github.com/kubernetes/dns/blob/master/docs/specification.md).   So it can replace `pods verified` in the _kubernetes_ plugin, thus using a single Pod watch.
