### ISSUE TITLE
plugin/forward: configurable healthcheck domain support

### ISSUE THREAD

**Issue by stevo-f3** [miekg/coredns#5121]
**What would you like to be added**:

Make domain used by forward plugin's upstream health check configurable.

**Why is this needed**:

Currently forward plugin health check resolves `.` (see https://coredns.io/plugins/forward/#description). Configuring DNS firewalls to allow `.` to be resolvable, and not have that interpreted as allow all domains is not always possible.

**Comment by hansedong** [comment]
I think this issue is worth discussing and supporting. 
For example, when a group of my CoreDNS servers are deployed in the company's internal network, and it is not connected to the external network, and its upstream DNS Server is also in the internal network, at this time, there is no need to force the sending of .NS records as Probe request.
@yongtang @miekg  How do you feel about this scene? If this proposal works, can I submit a PR to resolve this issue?

**Comment by chrisohaver** [comment]
@stevo-f3 , are you planning to open a PR for https://github.com/stevo-f3/coredns/commit/9e31ed1abbda8e4fb5a36088805c293fb9f559e0 ?

**Comment by chrisohaver** [comment]
IIRC (from slack discussion), @stevo-f3 ‘s use case was for making it easier to permit health checks through dns firewalls that would block all root queries.

IMO this is a reasonable option to add. @hansedong , it looks like @stevo-f3 has already made this change locally in his branch and may want to open a PR for it.

**Comment by hansedong** [comment]
@chrisohaver Thank you very much for your reply. I read the committed code by @stevo-f3 , however, the customizable options for probing should also include the DNS request type (such as A record or CNAME, etc.) in addition to the domain. 
@stevo-f3 would you like to optimize the configurable items of health detection? Thank you very much for submitting a new PR, if any, otherwise I plan to reopen a PR.

**Comment by chrisohaver** [comment]
@hansedong , can you describe a scenario that requires customization of the type? It would be a simple add, but there should be a legitimate use case.

**Comment by hansedong** [comment]
@chrisohaver Sorry, I haven't come up with any actual scenarios. I just take it for granted that the dns request type is one of the options for health checks, just like the request type of health checks  in components such as Gateway and LVS (for example: HTTP, TCP).

**Comment by chrisohaver** [comment]
In this context the type doesn’t matter, since the health check just checks for any response, a record of that type doesn’t have to exist on the upstream server.

**Comment by hansedong** [comment]
@chrisohaver 


> In this context the type doesn’t matter, since the health check just checks for any response, a record of that type doesn’t have to exist on the upstream server.

I read the code, the logic is indeed like this, thanks for pointing out.

**Comment by hansedong** [comment]
@chrisohaver I submitted a PR #5281 , can you help review the code?

**Comment by chrisohaver** [comment]
@hansedong, lets give @stevo-f3 the courtesy of a few more days to respond.
