### ISSUE TITLE
CoreDNS Cache's serve_stale

### ISSUE THREAD

**Issue by roldancer** [miekg/coredns#5296]
Hi All, We are planning to use on Kubernetes the CoreDNS cache's serve_stale parameter for a custon forwarded zone, do you recommed to use serve_stale in production?, we want to improve DNS resilience.

Many thanks for your feedback

**Comment by chrisohaver** [comment]
Should be fine. Be aware that the way the `serve_stale` feature in CoreDNS works follows unbound's `serve-expired` implementation, not RFC-8767.

**Comment by chrisohaver** [comment]
> Be aware that the way the `serve_stale` feature in CoreDNS works follows unbound's `serve-expired` implementation, not RFC-8767.

Of note, by design the implementation favors fast response time over answer correctness.  It will always serve an expired cache entry (younger than DURATION), _before_ checking to see if there is an updated answer.  After responding with the expired entry, it resolves the request, and updates cache if it can resolve.  Therefore, it will respond with outdated answers  to clients until the cache updates (which can be incorrect if the record has changed since it was last cached).

For records that change frequently, an incorrect answer would occur more frequently. E.g. headless services in Kubernetes point to pod IPs, which are not very static (changing each time a pod is respawned). Although if only enabling `serve_stale` for a custom/private zone, Kubernetes records would of course not be affected.

If this caveat is acceptable, then it should be fine in production.

**Comment by roldancer** [comment]
Hi @chrisohaver, Many thanks for your feedback, do you know if someone is using CoreDNS cache's serve_stale parameter for a custon forwarded zone, I mean is there any enterprise reference?

Many thanks

**Comment by chrisohaver** [comment]
I personally don't have any enterprise references.

**Comment by roldancer** [comment]
Hi @chrisohaver , We are planning to use CoreDNS Cache's serve_stale parameter for a custom zone, this zone has DNS records with TTL of 1h, 8h and 24h, what are the most important recommendations or use case for Cache's serve_stale parameters keeping in mind that we need to improve DNS resilience. 
Many thanks in advance for any recommendation, guide, use case or real experience ....

Thanks.

**Comment by chrisohaver** [comment]
To allow CoreDNS to serve answers from cache for a DNS name in a private zone while that zone's DNS server is non-responsive, you will want to set the stale_cache duration to be about as long as the maximum time you would expect the zone's DNS server to be non-responsive.

I'd recommend enabling stale_cache only for the cache plugin in the private zone server block, not in the root server block that contains the kubernetes plugin.
