### ISSUE TITLE
Proper way to debug [INFO] plugin/ready: Still waiting on: "kubernetes" probe 503

### ISSUE THREAD

**Issue by alainpannetier** [miekg/coredns#5326]
What's the usual way to debug 

> [INFO] plugin/ready: Still waiting on: "kubernetes"

Especially without a shell to diagnose connectivity issues "from the inside", no root cause, nothing in the log.

coredns 1.8.6
k8s 1.23.5 just upgraded (all nodes).
Flannel cni plugin 1.0.1
Flannel cni  0.17.0
systemd-resolved enabled

**Comment by chrisohaver** [comment]
If you deploy 1.9.1, the logging is fixed/improved.

The “still waiting” log message means that the ready plugin is not reporting ready -> because the kubernetes plugin is not ready yet -> because it cannot sync with the k8s API, either because it can’t reach it, or can’t authenticate, or is unauthorized to list/watch the resources it needs.
