### ISSUE TITLE
Timeout error in coredns 

### ISSUE THREAD

**Issue by shruthidharani-4313** [miekg/coredns#5352]
As I am quite new to kubernetes environment, I am posting this question to understand what are the possibilities which might cause this kind of issues in coredns. I see the below error in the coredns pod logs and I haven't changed the default Corefile configuration. I have a rancher cluster deployed with multus-cni where multiple interfaces there in worker node.

```
[ERROR] plugin/errors: 2 774537368764142801.2119769806070251504. HINFO: read udp X.X.X.X:45662->Y.Y.Y.Y:53: i/o timeout
```

It would be really helpful if someone helps me to understand this problem. Thanks in advance!

**Comment by chrisohaver** [comment]
It means that CoreDNS is not getting a response from 10.93.16.71 before timing out.  At start up, CoreDNS sends these HINFO requests to upstream nameservers to detect forwarding loops (to ensure that queries don't get sent back to coredns in an infinite loop).

It's possible that 10.93.16.71 is ignoring the requests for some reason: e.g. if it's ignoring HINFO requests, ignores requests outside a limited set of zones, blocked by ACL, etc. However since you have an atypical CNI deployment, it's perhaps more likely that the requests are never reaching 10.93.16.71 (some sort of network misconfiguration, requests misrouted or dropped).

To troubleshoot:

1. Create a pod in your cluster with a shell and dns client tools installed (e.g. dig) 
2. from that pod, test dns queries directly to 10.93.16.71 (try A and HINFO types, and also queries for purely numeric domains as is done in the error messages e.g. `774537368764142801.2119769806070251504.`, and try known public names, and private domains if that server serves private domains).
3. from that pod,  do the same for queries to the coredns cluster dns service.

**Comment by shruthidharani-4313** [comment]
@chrisohaver Thanks, when I install dnstools to check dns resolution, it is working properly since dnstools pod will have only single interface (eth0). But in my case it is multi interface and have added routes to reach that dns server. When I directly dig to that server (dig @server) works fine but when it goes via kubernetes nameserver it is not.

**Comment by chrisohaver** [comment]
Ok. It’s pretty clear then that this issue is caused by your multi interface CNI configuration.  This is not caused by CoreDNS.

**Comment by shruthidharani-4313** [comment]
@chrisohaver Okay thanks, will check once with my CNI configuration
