### ISSUE TITLE
FQDN as dnstap TCP endpoint

### ISSUE THREAD

**Issue by mosajjal** [miekg/coredns#5355]
**What would you like to be added**:
At the moment, `coredns` supports `dnstap` with Unix sockets and TCP, which is awesome. however, the TCP support looks to be limited to IP:PORT. It would be useful to have `dnstap` with a FQDN remote socket, something like below:

`dnstap tcp://my-service.kube-system.svc.cluster.local:5000 full`

**Why is this needed**:

This makes it easier to manage `dnstap` logger pods in a k8s environment using the Service object type. At the moment there's a need to extract the Static IP of the service/pod and manually populate the ConfigMap which is not ideal.

**Comment by chrisohaver** [comment]
Should note that the example here shows a `cluster.local` address.  If this is intended to work from the Kubernetes cluster service deployment of CoreDNS, it would need to "use itself" to resolve the name.   This would result in an error logged when coredns starts, since when dnstap first tries to dial , CoreDNS will not have started listening yet (but if I read the code correctly, should re-dial successfully shortly after CoreDNS finishes starting).

**Comment by chrisohaver** [comment]
> FQDN as dnstap TCP endpoint

IIUC, you can already do this, but the system resolver is used, which in the standard k8s deployment of coredns are the upstream DNSs and those cannot resolve `cluster.local`.

**Comment by mosajjal** [comment]
Thanks for the input. I tried `dnstap tcp://localhost:5000` as a test just now and I still can't get it started. Although you're right that it tries to solve `localhost` against itself (my DNS setting is pointing to 127.0.0.1).

**Comment by chrisohaver** [comment]
>  I tried dnstap tcp://localhost:5000 as a test just now and I still can't get it started

That's not what I meant to suggest.  I was saying that the FQDN needs to be _resolved_ by CoreDNS ... not that the fqdn itself needs to be CoreDNS.  When an application makes a network connection to an FQDN endpoint, the first step is to resolve the FQDN to an IP address. Once it has an IP it can make a network connection to the endpoint.  In the cluster.local case, only CoreDNS can resolve that name to an IP.

**Comment by chrisohaver** [comment]
~IOW, the feature requested already works for FQDNs that can be resolved by the system resolver.~ Not the case, since parsing prohibits host names being passed to the dialer. 

But, the example given `my-service.kube-system.svc.cluster.local ` is not a name that can be resolved by CoreDNS's system resolver (in the context of kubernetes).  One way to get that to work is to add a new option to dnstap plugin to specify an alternate resolver for the dialer.  This limitation doesn't only apply to dnstap, it also applies to any plugin that makes a connection using an FQDN.  

A perilous solution would be configure the upstream namservers to forward queries in `cluster.local` back to CoreDNS. I'm not recommending this, just mentioning it here to help illustrate the issue.
Another way would be to set up an out-of cluster coredns instance with the kubernetes plugin enabled, so it can answer names in `cluster.local`, and configure the upstream namservers to forward queries `cluster.local` to that instance.

**Comment by mosajjal** [comment]
@chrisohaver, 

> > I tried dnstap tcp://localhost:5000 as a test just now and I still can't get it started
> 
> That's not what I meant to suggest. I was saying that the FQDN needs to be _resolved_ by CoreDNS ... not that the fqdn itself needs to be CoreDNS. When an application makes a network connection to an FQDN endpoint, the first step is to resolve the FQDN to an IP address. Once it has an IP it can make a network connection to the endpoint. In the cluster.local case, only CoreDNS can resolve that name to an IP.

yep I get that. what I wanted to demonstrate was the fact that even localhost (which is present in /etc/hosts and doesn't even need a DNS lookup necessarily) is not an accepted FQDN for dnstap. That leads me to believe no FQDN as a dnstap TCP endpoint will work. I'll do more digging to see if I can spot a DNS request coming from `coredns` trying to resolve the  dnstap FQDN but I doubt it even gets to that point.

**Comment by chrisohaver** [comment]
>  and I still can't get it _started_

Ah OK, CoreDNS doesn't _start_.  I incorrectly assumed it wasn't working due to a connection failure.
In that case it must be that dnstap is rejecting hostnames at config parsing.

**Comment by mosajjal** [comment]
Yeah that's my assumption too.

**Comment by chrisohaver** [comment]
@mosajjal, with the fix in #5377, you can [configure an upstream DNS to be able to resolve cluster service names](https://github.com/coredns/coredns/issues/5355#issuecomment-1118041764) to get this to work.  Or use the method described by @lobshunter, https://github.com/coredns/coredns/pull/5377#issuecomment-1125144541 (which I think works better despite feeling precarious, and is definitely easier).

**Comment by mosajjal** [comment]
Thanks @chrisohaver for the quick fix and looking into it. as you mentioned, this is probably the issue with more than just this plugin so maybe this'll become a template for plugin developers as well. using FQDN in dns config is always a chicken and egg problem so don't think it's gonna have an elegant solution anyway. I'll close this but feel free to re-open it if there are more PRs coming :)
