### ISSUE TITLE
Docker image digest not listing the correct architecture

### ISSUE THREAD

**Issue by vivkong** [miekg/coredns#5363]
**What happened**: 
The "OS/Arch" labels for each arch-specific image digest are incorrect for the newer tags (1.9.x)  on https://hub.docker.com/r/coredns/coredns/tags.

**What you expected to happen**:
It should show the correct arch for each digest like v1.8.7

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:

- the version of CoreDNS:
- Corefile:
- logs, if applicable:
- OS (e.g: `cat /etc/os-release`):
- Others:

**Comment by chrisohaver** [comment]
Starting with 1.9.0, we have changed the way the CoreDNS docker image is built (#5146). While the build script itself is unchanged, the build is now executed as a GitHub Action on GitHub Action infrastructure.  Previously it was built on dedicated hardware hosted in Packet.net.  Perhaps a difference in docker version is triggering this? Or perhaps docker configuration difference (e.g. experimental )?

**Comment by chrisohaver** [comment]
> Starting with 1.9.0, we have changed the way the CoreDNS docker image is built (#5146). 

Strike that.  It looks like the releases are still being done the old way.   I guess the new way (release triggered GitHub actions) did not succeed for 1.9.0 and 1.9.1, so we fell back on doing it the prior way for those releases.

**Comment by chrisohaver** [comment]
> I guess the new way (release triggered GitHub actions) did not succeed for 1.9.0 and 1.9.1

Yes, those actions failed before uploading images: https://github.com/coredns/coredns/actions/workflows/docker.yml
So the 1.9.0/1.9.1 releases were done manually using the same infra that 1.8.7 was built on.

I don't see any other build related changes between 1.8.7 and 1.9.0.  And per docker build logs, the docker version was not changed on the build infra between those versions.

**Comment by chrisohaver** [comment]
1.9.2 just released, also has wrong arch tags per https://hub.docker.com/r/coredns/coredns/tags

**Comment by mdemierre** [comment]
Note that one side-effect of this issue is that in the Docker Desktop managed Kubernetes, coredns is the only remaining container to use an emulated AMD64 image on Apple M1. I think that because of the structure of images and manifests, only the amd64 image is available. That's how I stumbled on this issue.

Ideally, the result of solving this issue should be to have only one image on the Docker Hub (https://registry.hub.docker.com/r/coredns/coredns), with different archs for the same tag. That way when a client pulls the image, the native architecture for the client would be selected.

Currently there are the following separate images for ARM:

- https://hub.docker.com/r/coredns/coredns-arm (shows up as amd64 arch)
- https://hub.docker.com/r/coredns/coredns-arm64 (shows up as amd64 arch)

From a quick look at the Makefile.docker and the Github action, I think all images are built on an AMD64 host: the ubuntu-latest image running on the standard Github action runners. I'm not sure exactly how the current workflow of building and pushing on AMD64, then changing the manifest and pushing it works.

The PR #5413 shows one possible solution, which is to use BuildKit cross-compilation capabilities to correctly build  images by specifying the architecture. Then Buildkit will take care of pulling the right architecture of the base image for the docker build, and to setup the correct manifest.

Another solution would be to spawn different runners each for a specific architecture, such as building the ARM64 image on a ARM64 GitHub action runner. I'm not familiar enough with Github actions to know if this is feasible, especially since coredns supports many architectures. From my quick research, it seems if one wants to do that they need to bring their own runners.

So in my opinion PR #5413 is the easiest solution and is on the right track.
