### ISSUE TITLE
Warn of potentially malformed domains in Corefiles

### ISSUE THREAD

**Issue by agurgel-te** [miekg/coredns#5386]
[Via a Slack conversation](https://cloud-native.slack.com/archives/C4DF7FP71/p1652741093205869) with @chrisohaver.

**What you would like to be added**: A warning about potentially malformed domains in `Corefile`s: e.g., `k8s.foo.bar.com::53` (with two colons). 

**Why this is needed**: CoreDNS will parse the domain as if `com:` were a valid domain ([it technically is](https://cloud-native.slack.com/archives/C4DF7FP71/p1652753134359439?thread_ts=1652741093.205869&cid=C4DF7FP71)), and serve requests referencing `k8s.foo.bar.com` elsewise, probably using the default provider. In my specific case, this resulted in `NXDOMAIN`s when `Pod`s tried to resolve cluster-local `Service`s.

**Comment by chrisohaver** [comment]
Domain names can occur in different places in the Corefile, and since each plugin parses their own section independently, implementing such warnings for all domain names would need to touch every plugin that accepts a domain name as an argument.

This is certainly doable for just server block domains.

We'd need to agree on what constitutes "potentially malformed".

**Comment by chrisohaver** [comment]
From https://datatracker.ietf.org/doc/html/rfc1035#section-3.1 :

```
Although labels can contain any 8 bit values in octets that make up a
label, it is strongly recommended that labels follow the preferred
syntax described elsewhere in this memo, which is compatible with
existing host naming conventions.
```

So, perhaps we can warn when a domain doesn't match the "preferred
syntax described elsewhere in this memo,"  which is...

From https://datatracker.ietf.org/doc/html/rfc1035#section-2.3.1 :
```
<domain> ::= <subdomain> | " "

<subdomain> ::= <label> | <subdomain> "." <label>

<label> ::= <letter> [ [ <ldh-str> ] <let-dig> ]

<ldh-str> ::= <let-dig-hyp> | <let-dig-hyp> <ldh-str>

<let-dig-hyp> ::= <let-dig> | "-"

<let-dig> ::= <letter> | <digit>

<letter> ::= any one of the 52 alphabetic characters A through Z in
upper case and a through z in lower case

<digit> ::= any one of the ten digits 0 through 9
```

**Comment by chrisohaver** [comment]
I think this is OK to do directly in dnsserver startupZones().

However if there are concerns for this warning being a nuisance to the theoretical user who is intentionally using non-preferred format domains,  it could instead be done in a plugin. E.g. in _debug_, which could check the domains from the enclosing server block and print warnings during startup.

**Comment by chrisohaver** [comment]
> I think this is OK to do directly in dnsserver startupZones().
> 
> However if there are concerns over this warning being a nuisance to the theoretical user who is intentionally using non-preferred format domains, it could instead be done in a plugin. E.g. in _debug_, which could check the domains from the enclosing server block and print warnings during startup.

**Comment by mdsahiloss** [comment]
@chrisohaver I would like to work on this issue

**Comment by mdsahiloss** [comment]
@chrisohaver Are you sure? You want warning implementation in dnsserver startupZones() because I'm new to coredns ( I'll learn it by fixing issues and reading docs) and I don't know whether it will reflect to user or not when user will malform **Domain Name** .

If yes then I can implement warning in `startupZones()` by using Regex.

**Comment by chrisohaver** [comment]
> @chrisohaver Are you sure? You want warning implementation in dnsserver startupZones() because I'm new to coredns ( I'll learn it by fixing issues and reading docs) and I don't know whether it will reflect to user or not when user will malform **Domain Name** .
> 
> If yes then I can implement warning in `startupZones()` by using Regex.

Just a suggestion. If you think of a better way, go ahead.

**Comment by Wowbagger15** [comment]
Good day,

Excuse my ignorance, but how would I go about suggesting to follow/implement [RFC 1123](http://www.faqs.org/rfcs/rfc1123.html), specifically paragraph 2.1 and outlined in [this overview](https://cs.uwaterloo.ca/twiki/view/CF/HostNamingRules#RFC1123), instead of RFC 1035 ? Should I reopen this issue or create a new one referencing this work?

I am a small CoreDNS user that happens to have a few domains starting with a digit. Althought they are only warnings, IMHO it seems best to reference the most recent uptake on host names and DNS components:

```
From RFC-952
      <name>  ::= <let>[*[<let-or-digit-or-hyphen>]<let-or-digit>]
or From RFC-1039
     <label> ::= <letter> [ [ <ldh-str> ] <let-dig> ]
To RFC-1123
      <name>  ::= <let-digit>[*[<let-or-digit-or-hyphen>]<let-or-digit>]

```

Kind regards,

Bob de Vries

**Comment by chrisohaver** [comment]
@Wowbagger15,  You can open a new issue. Or since it’s probably a small tweak, just jump straight to opening a PR if you can.
