### ISSUE TITLE
Using multiple server blocks with groups of records in a zone, what would be the best way to configure DNSSEC?

### ISSUE THREAD

**Issue by benperove** [miekg/coredns#5389]
Hello! I'm using CoreDNS as an authoritative public nameserver and I'm trying to implement DNSSEC for zone example.com. I have a few additional server blocks responsible for serving groups of A records in the same zone. I have a Corefile similar to the following:
```
example.com {
    dnssec {
        key file Kexample.com.+013+35468
        key file Kexample.com.+013+43082
    }
    file db.example.com #contains SOA/NS/DNSKEY/DS records
}

subdomain-a.example.com {
    dnssec {
        key file Ksubdomain-a.example.com.+013+35468
        key file Ksubdomain-a.example.com.+013+43082
    }
    custom_plugin subdomain-a.yaml #serves only A/AAAA/CNAME records for subdomain-a.example.com
}

subdomain-b.example.com {
    dnssec {
        key file Ksubdomain-b.example.com.+013+59523
        key file Ksubdomain-b.example.com.+013+45972
    }
    custom_plugin subdomain-b.yaml #serves only A/AAAA/CNAME records for subdomain-b.example.com
}
```
I've tried adding DNSKEY and DS records for the subdomains to db.example.com and I've also tried to inline with the records plugin, but I've not yet been able to make it work 100% (and appease _all_ of the DNSSEC toolboxes of the Internet).

I realize that it would be easier to put everything all in the same zone, but at present, file & custom_plugin don't play nice together, so I set up the additional server blocks to handle that part. Without DNSSEC everything's working properly, but when it's enabled, it seems like the server blocks are being treated as separate zones.

Do I have the right approach with this configuration, or should I do things differently?

**Comment by chrisohaver** [comment]
The issue with the proposed solution could be due to the _dnssec_ plugin always marking the signer as the enclosing zone.  This means the signer in the RRSIGs from the subdomains differ from each other and the parent zone.  I'd think it would not matter since a validator would just pull the corresponding DNSSEC key and validate. But perhaps this is confusing some resolvers since normal this mismatch would only happen during delegation (which isn't happening in this configuration).

The following should (I didn't test it though) sign all records as if they were signed from `example.com.`  No delegation used here. It does use self forwarding which is a bit of a kludge.

```
example.com {
    dnssec {
        key file Kexample.com.+013+35468
        key file Kexample.com.+013+43082
    }
   forward . localhost:5353
}

example.com:5353 {
    file db.example.com
}

subdomain-a.example.com:5353 {
    custom_plugin subdomain-a.yaml #serves only A/AAAA/CNAME records for subdomain-a.example.com
}

subdomain-b.example.com:5353 {
    custom_plugin subdomain-b.yaml #serves only A/AAAA/CNAME records for subdomain-b.example.com
}
```

To instead do this using delegation, coredns needs to bind each zone to separate addresses (with bind plugin), and the parent would delegate the subdomains to the other addresses, and hold DS records for each subdomain. This is essentially the same as running 3 different coredns servers.  Trying to do it this way all from one server or shared address is problematic due to the way queries get routed to the server blocks.

**Comment by chrisohaver** [comment]
> ... file & custom_plugin don't play nice together ...

Perhaps worth digging here to determine why, and resolving it so they do.

**Comment by benperove** [comment]
> This means the signer in the RRSIGs from the subdomains differ from each other and the parent zone.

That's exactly what I was running into.

@chrisohaver your proposed Corefile works exactly as I had hoped. This will also be easier to maintain as there will be fewer ZSKs to roll over. You're also correct regarding the other plugin, but it's not a high priority at the moment. Thanks for taking a look!
