### ISSUE TITLE
why CoreDNS use MaximumDefaulTTL(3600s) as the max ttl of rrset ?

### ISSUE THREAD

**Issue by IIvyPy** [miekg/coredns#5436]
Most authority rrset is 7days, like root record. 
I don't understand why CoreDNS set 3600s as the max ttl.
Thank you for your answers!

**Comment by chrisohaver** [comment]
Are you facing a specific scenario where this is causing a problem? If so, please share.

I don't think anyone knows the original reasoning.   But due to the way that CoreDNS's cache works, the low ceiling doesn't usually matter that much.  Unlike most other DNS caches that cache individual records/recordsets, CoreDNS caches entire responses, and thus must choose a single TTL for the whole response.   It picks the shortest TTL when doing this (to avoid caching any parts of the response for longer than their respective TTLs).  So, unless the SOA record is directly queried, a lower TTL from another record in the response will be used.
