### ISSUE TITLE
Loop detected on EKS Fargate cluster

### ISSUE THREAD

**Issue by nicon89** [miekg/coredns#5473]
**What happened**:
I'm having issues with installing coredns plugin on Fargate based EKS cluster.
```
$ k get pods -n kube-system -w
NAME                       READY   STATUS             RESTARTS   AGE
coredns-7f78f64497-7fz6q   0/1     Error              3          2m5s
coredns-7f78f64497-ln8t7   0/1     CrashLoopBackOff   3          2m35s
coredns-7f78f64497-7fz6q   0/1     CrashLoopBackOff   3          2m8s
$ k logs -f -n kube-system coredns-7f78f64497-ln8t7 
.:53
[INFO] plugin/reload: Running configuration MD5 = 47d57903c0f0ba4ee0626a17181e5d94
CoreDNS-1.8.4
linux/amd64, go1.13.15, 053c4d5c
[FATAL] plugin/loop: Loop (127.0.0.1:56162 -> :53) detected for zone ".", see https://coredns.io/plugins/loop#troubleshooting. Query: "HINFO 3928026018829298329.8744627289841445895."
```
**What you expected to happen**:
It should work.

**How to reproduce it (as minimally and precisely as possible)**:
Setup EKS cluster with Fargate runtime. Enable CoreDNS addon.

**Anything else we need to know?**:

**Environment**:

- the version of CoreDNS: v1.8.4-eksbuild.1
- Corefile:
- logs, if applicable:
- OS (e.g: `cat /etc/os-release`): Kubernetes 1.21
- Others:

**Comment by chrisohaver** [comment]
This means a forwarding loop is present. It more or less means an upstream is forwarding queries from CoreDNS back to CoreDNS, or (more frequently the case) CoreDNS is configured to forward queries to itself.  Forwarding loops are bad.
 
Does https://coredns.io/plugins/loop#troubleshooting provide any clarity?

**Comment by nicon89** [comment]
Unfortunately it doesn't help much as this is serverless K8s (fargate) - I don't have access to host node.

**Comment by chrisohaver** [comment]
I suspect this is a problem with Fargate hosts, that they have a local caching dns installed (as described in https://coredns.io/plugins/loop#troubleshooting), and kubelet is setting up pods with the wrong `resolv.conf`.
 
If you cannot fix that in kubelet or the host, then the "quick and dirty" fix described in https://coredns.io/plugins/loop/#troubleshooting can side-step the configuration issue - i.e. specify the upstream servers manually instead of using "/etc/resolv.conf".

**Comment by javier-diaz-ppro** [comment]
With the help of AWS support ended up using the "quick and dirty" method, according to them this might be due to a change made on DNS caching configuration to avoid throttling.

EKS coredns add-on creates coredns config map in kube-system namespace, you can edit it and replace the /etc/resolv.conf with the VPC resolver IP
`For example, the Amazon DNS Server on a 10.0.0.0/16 network is located at 10.0.0.2`
(https://docs.aws.amazon.com/vpc/latest/userguide/vpc-dns.html)

This is how my config map looks like after the change:

```
apiVersion: v1
data:
  Corefile: |
    .:53 {
        errors
        health
        kubernetes cluster.local in-addr.arpa ip6.arpa {
          pods insecure
          fallthrough in-addr.arpa ip6.arpa
        }
        prometheus :9153
        forward . 10.10.0.2
        cache 30
        loop
        reload
        loadbalance
    }
kind: ConfigMap
metadata:
  labels:
    eks.amazonaws.com/component: coredns
    k8s-app: kube-dns
  name: coredns
  namespace: kube-system

```

After the change just recreate the pods and that will do it.
