### ISSUE TITLE
bind 公网ip coredns forword不工作

### ISSUE THREAD

**Issue by chen2ding** [miekg/coredns#5497]
bind 公网ip coredns forword 不工作。没日志输出，bind内网ip就正常

**Comment by Tantalor93** [comment]
shooting question in Chinese expecting us to understand it is not very polite 🙂 
```
bind public network ip coredns forword does not work. No log output, bind intranet ip is normal
```
your issue is not very well described, see https://github.com/coredns/coredns/blob/master/.github/CONTRIBUTING.md#bug-reports. For now I am closing this issue to mitigate these wild not very good formulated questions to set an example 🙂  If your problem persists I suggest you open the issue with more info like CoreDNS version, CoreDNS logs, OS version,...  and even better try to use English 🙂
