### ISSUE TITLE
Forward: Allow modification of query flags (e.g. always set RD)

### ISSUE THREAD

**Issue by jarus** [miekg/coredns#5548]
**What would you like to be added**:
Allow modification of DNS query flags within the forward plugin. Especially, I would like to set the RD (Recursion Desired) flag so that an upstream DNS server performs internal recursive resolution even the client or another recursive resolver didn't request recursive resolution.

**Why is this needed**:
I'm currently building a rewrite/forward setup towards the internal AWS EC2  and GCP VM DNS servers to allow resolution of EC2 or GCP VM instance names within an existing DNS infrastructure.

Overview and query path:
* Client: Queries `i-abcdef12345.aws-eu-west-1.example.com` through existing On-Prem DNS infrastructure
* On-Prem DNS Recursive Resolver (arbitrary recursive DNS resolver e.g. unbound/bind): Through `NS` records for `aws-eu-west-1.example.com` it knows which "authority nameserver" or in this case On-Prem DNS Forwarder servers should be queried.
* On-Prem DNS Forwarder (CoreDNS) acts as authority for `aws-eu-west-1.example.com` and forwards the query to another CoreDNS server in the AWS VPC. This may sound overkill but allows to use DNS over TLS, caching etc. on the On-Prem DNS Forwarder.
* CoreDNS server in AWS VPC rewrites query from `i-abcdef12345.aws-eu-west-1.example.com` to `i-abcdef12345.eu-west-1.compute.internal` and forwards query to AWS EC2 DNS server (169.254.169.253).
* AWS EC2 DNS server (169.254.169.253): Resolves `i-abcdef12345.eu-west-1.compute.internal` and generate response

Thanks to CoreDNS's rewrite and forward plugins this already works great for GCP but often fails with AWS EC2 DNS server. After multiple hours debugging and reading Wireshark captures, I identified the problem. The On-Prem DNS Recursive Resolver queries without the RD flag (Recursion Desired) as it would perform the recursive resolution. All CoreDNS instances (on-prem and in AWS) correctly forward the query without the RD flag to the AWS EC2 DNS resolver. What I learned is that the AWS EC2 DNS server (169.254.169.253) is also a recursive DNS server. If it has no cache entry for `i-abcdef12345.eu-west-1.compute.internal`, it must perform a recursive DNS resolution. Without the RD flag, the AWS EC2 DNS server just provides a list of root servers and assumes the client will perform the required recursive resolution. If a client explicitly queries the On-Prem DNS Forwarder with the RD flag, the RD flag is transported though the forward chain and the AWS EC2 DNS server provides the correct answer. This also updates its internal cache and subsequent queries from the On-Prem DNS Recursive Resolver without the RD flag also receive a valid response until the cache expired.

The same setup already works for GCP as the GCP DNS service doesn't care about the `RD` flag and acts like an authority nameserver.

Eventually, I would like to instruct the forward plugin to set the RD flag so that the AWS EC2 DNS server always perform internal recursive resolution.

Thoughts and opinions about the idea would be highly appreciated. My Go skills are limited but I could try to provide an initial pull request with such an enhancement.

**Comment by johnbelamaric** [comment]
Perhaps this would be better in the `rewrite` plugin or as its own plugin?

**Comment by mqasimsarfraz** [comment]
Or we can extend `header` [plugin](https://coredns.io/plugins/header/) to also allow overriding query flags? Currently it only allows to override responses.

**Comment by johnbelamaric** [comment]
+1

**Comment by mqasimsarfraz** [comment]
Perfect. @jarus please feel free to purpose a PR if you had some changes in mind. I would be happy to help/review the changes. Otherwise I can also draft an initial version. Introducing a selector like `query/response` in Corefile can be a good starting point:

```
. {
    header {
        query set rd
        response set aa
    }
}
```

**Comment by chrisohaver** [comment]
The one difference between doing this in _forward_, vs doing this in _header_ is that in *forward*, it would only be applied to requests going to upstream servers of _forward_.  Whereas with _header_, it would be applied before all other plugins process it.  It's a subtle difference: As of now, I don't think any _internal_ plugins care about the RD flag.

**Comment by mqasimsarfraz** [comment]
Thanks for pointing that out. Definitely if a following plugin overrides any flag, users will be left with an unexpected outcome. Although currently I don't see any plugin doing that.  Probably we can add a note in `header` plugin documentation? Otherwise we can allow setting RD flag in `forward` plugin config (which I am not sure is a great idea)? What do you think?

**Comment by chrisohaver** [comment]
> Definitely if a following plugin overrides any flag, users will be left with an unexpected outcome. 

Yes, there is that possibility too, although I think the more likely possibility is that a plugin would behave differently depending on the state of the RD flag rather than override the flag. e.g. A plugin performing recursion would probably check the RD flag (such a plugin does not exist in the CoreDNS repo currently).

IOW, two possibilities: downstream plugins reading the modified RD flag, and downstream plugins overwriting modified RD flag before forward processes it.

> Probably we can add a note in header plugin documentation?

I don't think either of those possibilities need to be documented, since it's apparent from the way it configured.  If for some reason, someone wants to set RD flag exclusively on upstream requests, they could either alter the execution order of header in plugin.cfg or use local forwarding (forward upstream to a local serve block that mutates the header and forwards upstream).

> Otherwise we can allow setting RD flag in forward plugin config 

I prefer implementing it in header.

Regarding request mutation in general: I wonder if there are any clients that will raise errors/warnings if an answer received has different request oriented flags (i.e. RD, CD) from what it had sent (like some do for question section and RR name changes).  I'm guessing probably not (but if we find there are, we can restore the original flags from request before writing to client).

**Comment by mqasimsarfraz** [comment]
> > Probably we can add a note in header plugin documentation?
> 
> I don't think either of those possibilities need to be documented, since it's apparent from the way it configured. If for some reason, someone wants to set RD flag exclusively on upstream requests, they could either alter the execution order of header in plugin.cfg or use local forwarding (forward upstream to a local serve block that mutates the header and forwards upstream).
> 

:+1: 
> > Otherwise we can allow setting RD flag in forward plugin config
> 
> I prefer implementing it in header.
> 
> Regarding request mutation in general: I wonder if there are any clients that will raise errors/warnings if an answer received has different request oriented flags (i.e. RD, CD) from what it had sent (like some do for question section and RR name changes). I'm guessing probably not (but if we find there are, we can restore the original flags from request before writing to client).

Yes, given we already implement `dns.ResponseWriter` in `header` we can easily restore the original flags if needed. I can test some scenarios during development as well. Let me draft an initial versions for the enhancement and let's see where it goes. Thanks for all the feedback! :+1:

**Comment by jarus** [comment]
Thank you all for considering my enhancement request. I created a first draft and pull-request with the required changes. Please note that this is actually my first contribution in Go and they are probably beginner's mistakes. Highly appreciate any kind of feedback or modifications.
