### ISSUE TITLE
Which versions of coredns are affected by CVE-2022-2835? Is there a restoration plan?

### ISSUE THREAD

**Issue by JingWoo** [miekg/coredns#5574]
CVE-2022-2835 was discovered by Red Hat on August 16，but there is no relevant description, has anyone researched it? Which versions of coredns does it affect？

https://access.redhat.com/security/cve/cve-2022-2835

**Comment by yongtang** [comment]
For reference, public security information (so far) can be found in https://github.com/coredns/coredns/blob/master/.github/SECURITY.md

**Comment by chrisohaver** [comment]
The CVE is incomprehensibly brief and vague. I really don't have an idea of what the issue actually is.  The links in the CVE did not lead to any further clarity.

Without more information, I cannot address this or assess its validity.

FWIW, AFAIK, Redhat did not reach out to CoreDNS before publishing this CVE publicly.

**Comment by chrisohaver** [comment]
I believe I've managed to infer what the CVE intends to convey, based on the suggested mitigation of adding an admission controller.  The concern raised actually falls within in Kubernetes' DNS service discovery schema, strictly not CoreDNS (e.g. it would also affect Kube-DNS, which also implements the K8s DNS Spec).

Per my understanding, the issue as reported claims that if a user creates a namespace named `svc`, it would collide with the [K8s DNS-Based Discovery Spec](https://github.com/kubernetes/dns/blob/master/docs/specification.md), and the resolv.conf search path constructed by kubelet and issued to pods by kubelet.  The CVE claims that if a malicious user was to add services into a namespace named `svc`, this collision could cause a pod's dns search (as expanded by its resolv.conf), to land on one of those services instead of the intended service.  However, I haven't yet managed to work out a scenario where this can actually occur. 

FWIW, IIUC the CVE is actually raised against a K8s related product offered by RedHat, not CoreDNS specifcally.

Summarizing: 
* While the collision potentially exists in K8s DNS schema, I'm not certain this actually can be exploited as described in the CVE.
* This really isn't an issue with CoreDNS in particular (it could be mitigated in CoreDNS, but also could be mitigated in K8s with an admission controller as suggested in the CVE)

**Comment by chrisohaver** [comment]
If a user creates a namespace that matches a _local/private domain_, this could cause an issue if a client makes an non-fqdn query for a host in that domain. E.g. When searching for non-fqdn `host.privatedomain`, and intermediate name would be `host.privatedomain.svc.cluster.local.` for which an answer will be produced if such a k8s service exists.

There is no practical way to _automatically_ prevent this scenario in CoreDNS.  However, a CoreDNS admin could manually configure CoreDNS to only create DNS records for services in a static list of namespaces (see the `namespace` option in the _kubernetes_ plugin).  Or, an admission controller in K8s that prevents namespaces from being created with names in a list of private domains.

Inversely, if a user has a real private domain actually named `svc`, this would collide with the K8s DNS schema, and real hosts within that private domain could be eclipsed by services in K8s.  I think this is a somewhat contrived and unlikely scenario. Nevertheless, I think the only practical solution in this specific case would be to not have a private domain named `svc`, else ensure all pods only make fqdn queries.

**Comment by JingWoo** [comment]
> 

Thank you for your patience in answering my question, and what about CVE-2022-2837? RedHat also did not give a fix 
https://access.redhat.com/security/cve/cve-2022-2837

**Comment by chrisohaver** [comment]
It’s the same issue. These are not flaws with coredns.  They illustrate exploitations of Kubernetes’ DNS ClusterFirst dnsPolicy, of which coredns takes no part other than happening to be the dns server that answers the dns queries. The “flaw” happens on the client side when the query is constructed, before being sent to coredns.
