### ISSUE TITLE
plugin/kubernetes should return an NXDOMAIN for missing TXT queries

### ISSUE THREAD

**Issue by LAMRobinson** [miekg/coredns#5736]
**What happened**:
TXT queries are incorrectly returning with an empty NOERROR response rather than NXDOMAIN. Beyond just being incorrect this matters because as a valid response it means that DNS clients won't try additional domains in their search path to hopefully find the right thing.

**What you expected to happen**:
CoreDNS should return an NXDOMAIN as the record doesn't exist

**How to reproduce it (as minimally and precisely as possible)**:
```
[]$ export CLUSTERDOMAIN=prod.cluster.local
[]$ dig foobarbaz.svc.$CLUSTERDOMAIN TXT @192.168.240.10 | grep status
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 45013
```

Expected:
```
[]$ dig foo.google.com TXT @8.8.8.8 | grep status
;; ->>HEADER<<- opcode: QUERY, status: NXDOMAIN, id: 53366
```

**Anything else we need to know?**:
This works properly for SRV and A records (anything the Kubernetes plugin actually supports):
```
[]$ dig foo.svc.$CLUSTERDOMAIN SRV @192.168.240.10 | grep status
;; ->>HEADER<<- opcode: QUERY, status: NXDOMAIN, id: 58698

[]$ dig foo.svc.$CLUSTERDOMAIN A @192.168.240.10 | grep status
;; ->>HEADER<<- opcode: QUERY, status: NXDOMAIN, id: 10092
```

**Environment**:

- the version of CoreDNS: 1.9.1
- Corefile:
```
.:53 {
    log
    errors
    health
    ready
    kubernetes prod.cluster.local
    forward . 8.8.8.8
    prometheus :9153
    cache 10
    loop
    reload
    loadbalance
}

```
- logs, if applicable:
- OS (e.g: `cat /etc/os-release`):
- Others:

**Comment by LAMRobinson** [comment]
Logged a PR (#5737) to fix this:
```
$ dig foobarbaz.svc.prod.cluster.local TXT @192.168.240.10 | grep status
;; ->>HEADER<<- opcode: QUERY, status: NXDOMAIN, id: 61083
```
vs current:
```
dig foobarbaz.svc.prod.cluster.local TXT @192.168.240.10 | grep status
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 24078
```

**Comment by chrisohaver** [comment]
The existing code is wrong. (i.e this is indeed a bug)

However strictly speaking, the correct response is dependent on the existence of other records.

For example, in a vanilla cluster with the cluster domain as `cluster.local` ...

* A TXT query for `kubernetes.default.svc.cluster.local` should result in NODATA, because an A record exists at the same name (in this case for the default kubernetes API service).
* A TXT query for `default.svc.cluster.local` should result in NODATA, since names exist "within" this domain, even though the domain itself has no records (this is also known as an empty non-terminal).
* A TXT query for `non-existing.svc.cluster.local ` should result in NXDOMAIN, if there is no exposed namespace named `non-existing`

**Comment by jordanrinke** [comment]
~~For anyone else running into this issue, we were able to put in a short term workaround for our use case (mongo atlas).~~ 
~~Not amazing but it works in k8s without applications needing any code changes.~~

~~Added to codedns config:~~

~~rewrite stop { name regex (.*)\.mongodb\.net\..+$ {1}.mongodb.net answer auto}~~

**Comment by chrisohaver** [comment]
I think a more general workaround would be to use the template plugin to match any TXT request in cluster.local and return NXDOMAIN. 

```
template IN TXT cluster.local {
  rcode NXDOMAIN 
}
```

**Comment by jordanrinke** [comment]
Tested, confirmed, much better solution. Appreciate it.
