### ISSUE TITLE
reverse plugin is not available

### ISSUE THREAD

**Issue by bkranendonk** [miekg/coredns#5775]
**What happened**: 

Im trying to use the `reverse` plugin as seen on the [CoreDNS website](https://coredns.io/plugins/reverse/). However the plugin does not seems to be included in CoreDNS.

CoreDNS returns  the following error message:

```
Corefile:2 - Error during parsing: Unknown directive 'reverse'
```

**What you expected to happen**:

I expected CoreDNS to start up and serve the statically set PTR record `ptrworks.com` for IPv4 address `10.10.10.1`

**How to reproduce it (as minimally and precisely as possible)**:

Start CoreDNS 1.10.0 with Corefile below

**Anything else we need to know?**:

**Environment**:

- the version of CoreDNS:
- Corefile:

```
arpa 10.10.10.0/24 {
    reverse {
        hostname ptrworks.com
    }
}
```

- logs, if applicable:
- OS (e.g: `cat /etc/os-release`): Windows 11 22H2
- Others: -

**Comment by chrisohaver** [comment]
_reverse_ was deprecated and removed some years ago (2018).  The same function can be accomplished with the _template_ plugin. https://coredns.io/plugins/template/#resolve-aptr-for-example

AFAIK, the CoreDNS website no longer links to the reverse plugin page. Although I assume due to a quirk with whatever process pushes updates from the coredns.io github repo to the web server, the orphaned page for it still remains, and thus some external sites may still point to it directly.

**Comment by bkranendonk** [comment]
Thanks for the swift reply. Is there another way to serve PTR records other than generating a zone file and use file plugin?

**Comment by chrisohaver** [comment]
Yes. If you are looking for the same function as the defunct _reverse_ plugin provided, that can [be accomplished with the _template_ plugin](https://coredns.io/plugins/template/#resolve-aptr-for-example).

If thats not what you are looking for, the _hosts_ plugin automatically generates reverse records for entries it defines.

**Comment by bkranendonk** [comment]
Thanks alot. Will look into those plugins :)
