### ISSUE TITLE
Metric coredns_forward_healthcheck_failures_total not found

### ISSUE THREAD

**Issue by DanielCastronovo** [miekg/coredns#5776]
**What happened**:
Prometheus metric coredns_forward_healthcheck_failures_total not found
**What you expected to happen**:
Find the metric :) 
**How to reproduce it (as minimally and precisely as possible)**:
curl on the /metrics

**Environment**:

- the version of CoreDNS: 1.8.7-eksbuild.2

**Comment by mariuskimmina** [comment]
What's the context?

There is a metric `coredns_forward_healthcheck_broken_total` maybe that can help you forward (at least it's there on 1.10).

There is also `coredns_health_request_failures_total` maybe you are mixing something up?

**Comment by chrisohaver** [comment]
Not certain if this is the case here, but some types of Prometheus metrics are only presented once they have been set. Iow, it’s possible the metric isn’t there because a failure has not yet occurred.

**Comment by DanielCastronovo** [comment]
The metric does not exist at all, there is no question of a null value :)

For more context i setup the mixin alert for Prometheus : https://github.com/monitoring-mixins/website/blob/0b456f10cc6091c5e9615a5a0e9c297ff842a0bd/assets/coredns/alerts.yaml#L89

I don't see any documentation on the metrics, and in the release not not containt any changelog, so it's difficult to follow if a metric has been created, deleted, etc.

**Comment by chrisohaver** [comment]
> The metric does not exist at all, there is no question of a null value :)

Not a null value, rather some metrics are not presented at all (aka don’t exist) in the metrics output until they are incremented.

**Comment by DanielCastronovo** [comment]
Why ? this is not the default behavior.
This can be a problem for alerts and dashboards if the metric does not exist.

A counter must be start at 0 by design IMO.

**Comment by chrisohaver** [comment]
I think it is the default Prometheus behavior unless the metric is manually initialized to zero.

**Comment by chrisohaver** [comment]
Digging a bit: this happens because a metric with labels will not always have a set of predictable (or even finite) label values, and thus we cannot always initialize every possible combination of labels to zero. When there are no labels for a counter, I think most implementations automatically initialize to zero.

In some cases where the set of labels is knowable in advance, we could iterate through them in coredns and initialize them to zero. But even if they are deterministic, the set of labels may be difficult to determine at the plugin scope. 

In this particular metric’s case, there is a single label “to”, which has a finite set of possible values and known at the plugin scope, so code could probably be added to initialize each one to zero.
