### ISSUE TITLE
plugin/kubernetes: no next plugin found

### ISSUE THREAD

**Issue by geotransformer** [miekg/coredns#5779]
CoreDNS 1.8.6

for "kubernetes coredns is in CrashLoopBackOff status when the /etc/resolv.conf is emtry"
https://github.com/coredns/coredns/issues/5764

Suggestion was to remove the forward plugin. 

```
apiVersion: v1
kind: ConfigMap
metadata:
  name: coredns
  namespace: kube-system
  labels:
    addonmanager.kubernetes.io/mode: EnsureExists
data:
  Corefile: |
    .:53 {
        errors
        health {
            lameduck 5s
        }
        ready
        kubernetes dns_domain in-addr.arpa ip6.arpa {
            pods insecure
            fallthrough in-addr.arpa ip6.arpa
            ttl 30
        }
        prometheus :9153
        reload
        loadbalance
    }
```
However, after that, still have some issue

```
===kubectl logs -n kube-system         coredns-6d4b75cb6d-pnql5   
.:53
[INFO] plugin/reload: Running configuration MD5 = 47becbcdb53a89983b43c3f6bcc9ddb5
CoreDNS-1.8.6
linux/amd64, go1.17.1, 13a9191
[ERROR] plugin/errors: 2 kubernetes.kube-system.svc.cluster.local. AAAA: plugin/kubernetes: no next plugin found
[ERROR] plugin/errors: 2 kubernetes.kube-system.svc.cluster.local. A: plugin/kubernetes: no next plugin found
[ERROR] plugin/errors: 2 kubernetes.kube-system.svc.cluster.local. AAAA: plugin/kubernetes: no next plugin found
[ERROR] plugin/errors: 2 kubernetes.kube-system.svc.cluster.local. A: plugin/kubernetes: no next plugin found
[ERROR] plugin/errors: 2 kubernetes.svc.cluster.local. AAAA: plugin/kubernetes: no next plugin found
[ERROR] plugin/errors: 2 kubernetes.svc.cluster.local. A: plugin/kubernetes: no next plugin found
[ERROR] plugin/errors: 2 kubernetes.svc.cluster.local. AAAA: plugin/kubernetes: no next plugin found
[ERROR] plugin/errors: 2 kubernetes.svc.cluster.local. A: plugin/kubernetes: no next plugin found
[ERROR] plugin/errors: 2 kubernetes. A: plugin/kubernetes: no next plugin found
[ERROR] plugin/errors: 2 kubernetes. AAAA: plugin/kubernetes: no next plugin found
[ERROR] plugin/errors: 2 kubernetes. AAAA: plugin/kubernetes: no next plugin found
[ERROR] plugin/errors: 2 kubernetes. A: plugin/kubernetes: no next plugin found
[ERROR] plugin/errors: 2 kubernetes. AAAA: plugin/kubernetes: no next plugin found
[ERROR] plugin/errors: 2 kubernetes. A: plugin/kubernetes: no next plugin found
[ERROR] plugin/errors: 2 kubernetes. AAAA: plugin/kubernetes: no next plugin found
[ERROR] plugin/errors: 2 kubernetes. A: plugin/kubernetes: no next plugin found
```

Add loop plugin back
```
apiVersion: v1
data:
  Corefile: |
    .:53 {
        errors
        health {
            lameduck 5s
        }
        ready
        kubernetes dns_domain in-addr.arpa ip6.arpa {
            pods insecure
            fallthrough in-addr.arpa ip6.arpa
            ttl 30
        }
        prometheus :9153
        loop
        reload
        loadbalance
    }

```

logs from the coredns pod
```
kubectl logs -n kube-system         coredns-6d4b75cb6d-rkzlh 
.:53
[ERROR] plugin/errors: 2 6132823676673281226.2099657313562268208. HINFO: plugin/loop: no next plugin found
[INFO] plugin/reload: Running configuration MD5 = 6a0cc89e0901ba2eb9772b4d035fe387
CoreDNS-1.8.6
linux/amd64, go1.17.1, 13a9191

**Comment by chrisohaver** [comment]
You also should remove the `fallthrough` line - since there is nothing to fall through to.

**Comment by geotransformer** [comment]
> fallthrough in-addr.arpa ip6.arpa

@chrisohaver thanks for your prompt reply. Another concern here is this error log
```
#
apiVersion: v1
data:
  Corefile: |
    .:53 {
        log
        errors
        health {
           lameduck 5s
        }
        ready
        kubernetes cluster.local in-addr.arpa ip6.arpa {
           pods insecure
           ttl 30
        }
        prometheus :9153
        loop
        reload
        loadbalance
    }
kind: ConfigMap
```


```
 kubectl logs -n kube-system         coredns-6d4b75cb6d-92s2r
[INFO] plugin/ready: Still waiting on: "kubernetes"
.:53
[INFO] plugin/reload: Running configuration MD5 = 68de2eb9592412d5ffc805ddf3033e9f
CoreDNS-1.8.6
linux/amd64, go1.17.1, 13a9191
[INFO] 127.0.0.1:36892 - 18409 "HINFO IN 4705057795563246423.3813990641589376207. udp 57 false 512" - - 0 0.000040685s
[ERROR] plugin/errors: 2 4705057795563246423.3813990641589376207. HINFO: plugin/loop: no next plugin found

**Comment by chrisohaver** [comment]
Yes - the loop plugin should also be removed. The loop plugin detects forwarding loops, and since there is no forwarding, it serves no purpose and throws this error when it tries to send test queries upstream.

**Comment by geotransformer** [comment]
> Yes - the loop plugin should also be removed. The loop plugin detects forwarding loops, and since there is no forwarding, it serves no purpose and throws this error when it tries to send test queries upstream.

@chrisohaver thanks. Looks good now
```
apiVersion: v1
data:
  Corefile: |
    .:53 {
        errors
        health {
            lameduck 5s
        }
        ready
        kubernetes cluster.local in-addr.arpa ip6.arpa {
            pods insecure
            ttl 30
        }
        prometheus :9153
        reload
        loadbalance
    }
```

**Comment by chrisohaver** [comment]
Looks like your domain is configured incorrectly. ‘dns_domain’ should be ‘cluster.local’

On Nov 25, 2022, at 10:52 PM, Vincent ***@***.***> wrote:

﻿
Yes - the loop plugin should also be removed. The loop plugin detects forwarding loops, and since there is no forwarding, it serves no purpose and throws this error when it tries to send test queries upstream. @chrisohaver Still not functional. 
ZjQcmQRYFpfptBannerStart
This Message Is From an External Sender
This message came from outside your organization.

ZjQcmQRYFpfptBannerEnd

Yes - the loop plugin should also be removed. The loop plugin detects forwarding loops, and since there is no forwarding, it serves no purpose and throws this error when it tries to send test queries upstream.

@chrisohaver<https://urldefense.com/v3/__https://github.com/chrisohaver__;!!JYsgTRAg6ZQ!IrcOnC8438d2D5-t97OE4Bmd5aJaVEf77nluLTPT8u1eS1UGH4BjxCjlLSiS7vDrblxqL9nrj4_agnlLySyQosFOkw$> Still not functional. Appreciate it if you can help one this one

apiVersion: v1
data:
  Corefile: |
    .:53 {
        errors
        health {
            lameduck 5s
        }
        ready
        kubernetes dns_domain in-addr.arpa ip6.arpa {
            pods insecure
            ttl 30
        }
        prometheus :9153
        reload
        loadbalance
    }


 kubectl exec -it dnsutils bash
kubectl exec [POD] [COMMAND] is DEPRECATED and will be removed in a future version. Use kubectl exec [POD] -- [COMMAND] instead.
***@***.***:/# nslookup kubernetes
Server:         10.96.0.10
Address:        10.96.0.10#53

** server can't find kubernetes.default.svc.cluster.local: SERVFAIL

***@***.***:/#

ERROR] plugin/errors: 2 kubernetes.default.svc.cee-global.svc.cluster.local. A: plugin/kubernetes: no next plugin found
[ERROR] plugin/errors: 2 kubernetes.default.svc.svc.cluster.local. AAAA: plugin/kubernetes: no next plugin found
[ERROR] plugin/errors: 2 kubernetes.default.svc.cluster.local. A: plugin/kubernetes: no next plugin found
[ERROR] plugin/errors: 2 kubernetes.default.svc.cluster.local. AAAA: plugin/kubernetes: no next plugin found
[ERROR] plugin/errors: 2 kubernetes.default.svc. A: plugin/kubernetes: no next plugin found
