### ISSUE TITLE
route53 plugin cannot resolve the alias A record

### ISSUE THREAD

**Issue by rookie-man-fack** [miekg/coredns#5830]
aws alias A record:

test.example.com  A    xxxx-nlb-x83db1738b.elb.us-west-2.amazonaws.com.

resolve:
{
  DNSName: "xxxx-nlb-x83db1738b.elb.us-west-2.amazonaws.com.",
  EvaluateTargetHealth: true,
  HostedZoneId: "Z18FSROUN"
}

func (h *Route53) updateZones(ctx context.Context) error {  

Alias A record update is not implemented

**Comment by chrisohaver** [comment]
Please provide more information so we can understand the issue you are encountering.

**Comment by rookie-man-fack** [comment]
aws route53  have a  alias A record   ，It can point domain names to aws internal services, similar to CNAME.  like : test.example.com  A  xxxx-nlb-x83db1738b.elb.us-west-2.amazonaws.com.  Normally, it should be resolved to an IP address


but route53 plugin "func (h *Route53) updateZones(ctx context.Context)"   The updated domain name is aws internal service domain name。

<img width="1190" alt="截屏2023-01-04 21 36 48" src="https://user-images.githubusercontent.com/110986345/210571045-d99d3c08-eb68-45a6-9746-d75e36dacb79.png">

**Comment by chrisohaver** [comment]
Thanks for clarifying. Looks like you want support added for "alias" records.  And I'm guessing that `updateZoneFromRRS` does not handle them because when it tries to parse the string representation of the A record, it chokes on the illegal value. 

FWIW, "alias" records are a pseudo type.  There does not actually exist a DNS record type called "alias".
Therefore if adding support for alias records, we'll need to decide how we would represent the alias with real DNS records.

E.g. when encountering an A record "example" with a hostname target "target":
1. translate it to a CNAME record. `example CNAME target`
2. OR translate it to a real A record. `example A 1.2.3.4`

Option 1 retains all information, but is fundamentally problematic since a domain name with a CNAME record must not contain any other records (of any type).  There would be some configurations we could not validly represent with CNAMEs, so I don't think this option is viable.

Option 2 loses the information about the target name (I don't think this is important). It also requires doing a lookup of the target during the update and inserting that IP into its zone (even though it's technically not managed by the zone). But it would allow multiple aliases for the same name along side real A records.

For option 2, I think the route53 plugin zone updates rebuild the zone from scratch, instead of incrementally updating, so cases like IP changes of the target probably don't need special handling. Also need to decide how to represent the TTL - probably use the lower of the target record TTL and the "alias" record TTL.

**Comment by rookie-man-fack** [comment]
Thank you very much for your answer. As you said, Alias A records that it is not a standard record value. I parsed the parsed CNAME again. You can close the issue.

**Comment by brekke-roq** [comment]
@chrisohaver 

My original issue here https://github.com/coredns/coredns/issues/5800 concerns non working geolocation records (where i also use aliases). Today i tried some simpler zones without geoip records and found this issue. Do you think that more complex dns record scenario (nested aliases + geoip +  whatever) will be ever handled by route53 plugin?

I have 2 region geolocation setup, 3 endpoints with health checks in each region so aliases are perfect way of making things as simple as possible and also efficient. Perhaps it would be to use CNAME records instead however pricing/performance impact is an open question.

Thanks!

**Comment by chrisohaver** [comment]
I don’t believe any current maintainers are currently working on this or planning to add it themselves, but a PR for alias support from the community would be welcome.

**Comment by Hronom** [comment]
Seems like it relates to this discussion here https://github.com/coredns/coredns/pull/3442 and this https://github.com/coredns/coredns/issues/3012 pretty much needed...
