### ISSUE TITLE
Docker Multiarch releases are stuck in v1.8.7

### ISSUE THREAD

**Issue by gaby** [miekg/coredns#5842]
It seems like most of the multiarch builds are stuck in v1.8.7 with no planed fixes

See: 
https://hub.docker.com/r/coredns/coredns/tags

Are there any plans from the CoreDNS team to address multiarch builds with their Docker images? This should be simple to do with buildkit. 

Looking at old issues, this issue is known since early 2022.

Rel: #5732 #5691 #5413 #5363 #5199

Docker Hub reports that coredns/coredns supports multiarch, but when looking at the latest tag we see this: 

![image](https://user-images.githubusercontent.com/835733/211321849-82a13975-c14d-4319-9d1a-c0d2c89446d3.png)

**Comment by gaby** [comment]
Cc. @yongtang

**Comment by chrisohaver** [comment]
A fix was merged ... https://github.com/coredns/coredns/pull/5691
There has not been a release since then. The latest release was cut before that fix merged.
The next release will include that fix, and thus should have the correct arch tags in the multi-arch manifest.
A precise date for the next release has not yet been determined, though based on cadence, I think we should do one this month.

**Comment by gaby** [comment]
@chrisohaver Thanks, looking forward to the next release

**Comment by iancward** [comment]
Looks like 1.10.1 was cut today.

**Comment by gaby** [comment]
Yes! It has fixed the issue

**Comment by Levi080513** [comment]
Have we considered dealing with tags that already have problems on Dockerhub, such as 1.9.3?
<img width="1290" alt="image" src="https://github.com/coredns/coredns/assets/114376205/eadc6400-2f62-4d41-a5e9-64e397d92082">

**Comment by chrisohaver** [comment]
I am a maintainer, but I don’t have write access to dockerhub. Perhaps someone with write access can address removing problem builds.

**Comment by Levi080513** [comment]
cc @yongtang
