### ISSUE TITLE
Use of the hash function to detect Corefile changes - replace it with SHA3-512

### ISSUE THREAD

**Issue by Pierre-Gronau-ndaal** [miekg/coredns#5914]
Description
The reload plugin is designed to automatically detect changes to a Corefile and to reload it
if necessary. To determine whether a file has changed, the plugin periodically compares the
current MD5/SHA-512 hash of the file to the last hash calculated for it
(plugin/reload/reload.go#L81-L107). If the values are different, it reloads the
Corefile.
However, the MD5/SHA-512 hash function’s vulnerability to collisions decreases the reliability of this
process; if two different files produce the same hash value, the plugin will not detect the
difference between them.

Exploit Scenario
An operator of a CoreDNS server modifies a Corefile, but the MD5/SHA-512 hash of the modified file
collides with that of the old file. As a result, the reload plugin does not detect the change.
Instead, it continues to use the outdated server configuration without alerting the operator
to its use.

Recommendations
Short term, improve the robustness of the reload plugin by using the SHA3-512 hash (https://en.wikipedia.org/wiki/SHA-3)
function instead of MD5/SHA-512.

**Comment by chrisohaver** [comment]
This isn't the first time the concern for config hash collision been raised.  In fact, the description above is copied word for word from last year's TOB security audit (with only encryption algos changed).

While I think the risk is very low, and IMO the vulnerability itself is not a cause for concern practically speaking, perhaps we should do a lossless comparison just to close this class of perceived problem.

**Comment by Pierre-Gronau-ndaal** [comment]
so that mean you have neither implement sha512 instead of md5, because there no concern practically speaking ...

the last time I heard a worldwide pandemic is not imaginable we got Corona ...

**Comment by chrisohaver** [comment]
If we do a lossless compare, there is zero chance for hash collision… because there isn’t a hash.

**Comment by aashh** [comment]
Collisions in cryptographic hash functions don't happen by accident, they happen in an attack scenario. However the issue posted above doesn't describe an attack scenario, it describes an accident.

**Comment by chrisohaver** [comment]
This issue could be framed as an attack scenario - but in that case, you must assume that attacker already has access to change CoreDNS's configuration. Given that prerequisite, the attacker would only be leveraging this exploit ensure that their malicious changes are _not_ immediately loaded by CoreDNS.  This is counter productive from the attacker's perspective, only loading the new config when CoreDNS restarts, not right away.  "Fixing" this would result in CoreDNS loading the malicious changes right away, which isn't better.

**Comment by polarathene** [comment]
> This isn't the first time the concern for config hash collision been raised.

Referencing your comment from Mar 2022 regarding `TOB-CDNS-6`:
https://github.com/coredns/coredns/pull/5226#pullrequestreview-901997267

I'm a little confused as this issue was opened after that was already merged last year?

---

> However, the MD5/SHA-512 hash function’s vulnerability to collisions decreases the reliability of this process

@Pierre-Gronau-ndaal

- Why are you saying MD5/SHA-512 when it's only SHA-512 in `reload.go`?
- What collision vulnerability exists that you are concerned about with SHA-512?

> _That means coredns may continues to use the outdated server configuration while operator may assume an updated version is in place._ - [Source](https://github.com/coredns/coredns/pull/5226#issuecomment-1059561223)

> _SHA3 isn't susceptible to length-extension attacks, which is useful in some cases (especially if you're doing the `MAC(K, X) = HASH(K || X)` construction, which is not okay to do with SHA2)._ - [Source](https://www.reddit.com/r/cryptography/comments/pipvk6/is_sha3512_safer_than_sha512/hbt3xya/)

Length extension attack [doesn't produce a collision](https://crypto.stackexchange.com/questions/75870/is-length-extension-attack-considered-as-collision). So what is the issue concerned about that SHA3 would resolve?

There is no known collision for SHA-512, nor SHA-256. The latter has roughly a little lower than 128-bit of resistance IIRC? While SHA-1 was below 80-bit which made it feasible to brute-force a collision (_with better attacks bringing the difficulty down to `2^64` / `2^64`_).

If similar vulnerability were found for SHA-256, you'd be looking at attacks that were still likely [**68 billion times more difficult** than SHA-1](https://github.com/docker-mailserver/docker-mailserver/issues/3456#issuecomment-1668877914), while the SHA-1 attack last I knew still cost thousands to perform, even if it could be accomplished for $1 USD, you can see how that is still ridiculously expensive to pull off.

SHA-512 should be fine. Should an exploit be discovered where that is no longer the case, I'm not sure how you could be confident that SHA3 would be any safer?

---

Given the above, this issue seems irrelevant and should be closed?

The attack is not pragmatic, there would be far more effective alternatives to resort to.

**Comment by SuperQ** [comment]
+1 to @chrisohaver's statement.

This is a non-issue as there is no clear attack vector / vulnerability to exploit here. The only thing a collision would do is _not_ do anything.
