### ISSUE TITLE
coredns should run as a non-root user

### ISSUE THREAD

**Issue by destijl** [miekg/coredns#5968]
Hi coredns folks,

Today the coredns container runs as root on the host, but it doesn't really need that level of privilege. Current security best practice is to run as an unprivileged user, which helps protect the host and other adjacent containers in case coredns is compromised by an attacker. @vinayakankugoyal sent a PR a couple of years ago to migrate it to an unprivileged user: https://github.com/coredns/coredns/pull/4528 but it didn't end up merging. From the comments on the PR I can't really tell why.

I'm filing this feature request so that hopefully we can get it migrated in the future. It would be great if coredns users were protected without having to figure out that non-root configuration for themselves.

I think Vinayak's code should still work if there's appetite to make the change.

Here's how you can verify that it's running as root today:

```
$ docker run coredns/coredns:latest
.:53
CoreDNS-1.10.1
linux/amd64, go1.20, 055b2c3
```

```
$ ps -C coredns -o user,uid,cmd
USER       UID CMD
root         0 /coredns
```

Vinayak and I are presenting about how to migrate containers to non-root in this Kubecon EU talk: https://sched.co/1HyX4

**Comment by johnbelamaric** [comment]
GKE doesn't run CoreDNS. But other  than that 100% agree. Thought we did this a long time ago!

**Comment by vinayakankugoyal** [comment]
I opened another PR to do this: https://github.com/coredns/coredns/pull/5969

**Comment by chrisohaver** [comment]
> @vinayakankugoyal sent a PR a couple of years ago to migrate it to an unprivileged user: https://github.com/coredns/coredns/pull/4528 but it didn't end up merging. **From the comments on the PR I can't really tell why.**

The comments show there was unresolved opposition from a couple of maintainers at the time to introducing buildx.

**Comment by destijl** [comment]
Thanks, updated comment about GKE. I thought this got on our radar through the GKE non-root effort, but it was through other work with kubeadm that vinayak came across it and tried to get it fixed.

**Comment by johnbelamaric** [comment]
Sure. We do run CoreDNS in Anthos clusters.

**Comment by destijl** [comment]
Woohoo! Thanks for getting it done!

**Comment by skrobul** [comment]
I reached this issue when searching why my Kubernetes cluster broke after restarting all nodes hosting CoreDNS pods with the following message:

```
Jun 01 09:52:24 app1 kubelet[43072]: E0601 09:52:24.172765   43072 pod_workers.go:965] "Error syncing pod, skipping" err="failed to \"StartContainer\" for \"coredns\" with CreateContainerConfigError: \"container has runAsNonRoot and image will run as root (pod: \\\"coredns-66c8db87cc-t6t2l_kube-system(184c66e7-ccaa-4a5b-bf9c-96c023a2f697)\\\", container: coredns)\"" pod="kube-system/coredns-66c8db87cc-t6t2l" podUID=184c66e7-ccaa-4a5b-bf9c-96c023a2f697
```

Turns out that Kubernetes enabled enforcement of  [PodSecurity](https://kubernetes.io/docs/concepts/security/pod-security-standards/) for the `kube-system` namespace at some point and it was just a ticking time bomb.

For anyone ending up here with the same problem, please note that despite this being fixed in https://github.com/coredns/coredns/pull/5969 there was no new release since then, and current newest version (v1.10.1) does not have that fix.

The solution for me was manually building the coredns image and updating `coredns` deployment in `kube-system` namespace to use that image. 

Possibly related: https://github.com/kubernetes/kubeadm/issues/2473
