### ISSUE TITLE
increase test coverage for `normalize.go`

### ISSUE THREAD

**Issue by khareyash05** [miekg/coredns#6093]
**What would you like to be added**:
I would like to add unit tests for `plugin/normalize.go`. Currently the test coverage is 57% [https://app.codecov.io/github/coredns/coredns/blob/master/plugin/normalize.go](https://app.codecov.io/github/coredns/coredns/blob/master/plugin/normalize.go)
**Why is this needed**:
To increase security

**Comment by chrisohaver** [comment]
Thanks - When adding these, keep in mind that some of the methods have been deprecated for a very long time. Those do not have coverage, and probably don't need to have coverage added since (IMO) we have given more than adequate runway at this point, and we should remove them in the next minor release.

**Comment by khareyash05** [comment]
> Thanks - When adding these, keep in mind that some of the methods have been deprecated for a very long time. Those do not have coverage, and probably don't need to have coverage added since (IMO) we have given more than adequate runway at this point, and we should remove them in the next minor release.

Thank you could you please help me where I can find the deprecated methods since I am new to this repo?

**Comment by chrisohaver** [comment]
They are the methods marked as deprecated the normalize.go comments.
