### ISSUE TITLE
SIGSEGV: on transfert on https

### ISSUE THREAD

**Issue by whoo** [miekg/coredns#6118]
Hi,

**What happened**: coredns stops with SIGSEGV on AXFR requests.

**What you expected to happen**: get zone via.
<code>~/go/bin/q -i @https://x.x.x.x -v example.org -t axfr</code>

**How to reproduce it (as minimally and precisely as possible)**:
<pre>

https://example.org:443 {
tls public.pem privkey.pem
file db.example.org
transfer {
 to *
 }

log
errors
}
</pre>

**Anything else we need to know?**: I'm running coredns from alpine on docker.
<pre>
/coredns/coredns --conf coredns
https://example.org.:443
CoreDNS-1.10.1
linux/amd64, go1.19.9,
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x40 pc=0x9da424]

goroutine 53 [running]:
github.com/coredns/coredns/core/dnsserver.(*DoHWriter).TsigTimersOnly(0x0?, 0x0?)
	<autogenerated>:1 +0x24
github.com/miekg/dns.(*Transfer).Out(0x0?, {0x14c2be0, 0xc0002085c0}, 0xc00031f9e0, 0x0?)
	/root/go/pkg/mod/github.com/miekg/dns@v1.1.54/xfr.go:220 +0x72
github.com/coredns/coredns/plugin/transfer.(*Transfer).ServeDNS.func1()
	/coredns/plugin/transfer/transfer.go:119 +0x36
created by github.com/coredns/coredns/plugin/transfer.(*Transfer).ServeDNS
	/coredns/plugin/transfer/transfer.go:118 +0x66c
</pre>

**Environment**:

- the version of CoreDNS:  CoreDNS-1.10.1
- OS (e.g: `cat /etc/os-release`): Alpine Linux v3.17

Thanks.

**Comment by Tantalor93** [comment]
Hello, this seems to be a combination of multiple issues/bugs and it seems only DoH is affected.

the main problem is in [DoHWriter](https://github.com/coredns/coredns/blob/master/core/dnsserver/https.go#L12) struct, which is embedding nonwriter, but in DoH server we are not providing [correctly initialized ](https://github.com/coredns/coredns/blob/master/core/dnsserver/server_https.go#L163)value for nonwriter, which leads to the panic. 

I think we can fix this by implementing it the same way it [is in GRPC server ](https://github.com/coredns/coredns/blob/master/core/dnsserver/server_grpc.go#L163), because currently the embedding on nonwriter does not make much sense and brings only these issues
