### ISSUE TITLE
Alias to a different domain resolved by an upstream DNS

### ISSUE THREAD

**Issue by maryo** [miekg/coredns#6140]
Hello. I want `*.test` to be an alias for `www` domain/hostname. IP of the `www` domain/hostname is known by an upstream DNS (IP specified in `/etc/resolv.conf`). `www` is actually a service inside docker compose project. I don't want to hardcode the IPs.

A simmilar question was answered in https://github.com/coredns/coredns/issues/1940 and the answer apparently helped the author of the question. But it does not work using the following configuration. I'm not using k8s so it could be caused by it. Is there a solution? Thank you very much for any advice.

`plugin/errors: 2 test.test. A: dns: bad A A: "www" at line: 1:22`

```Corefile
.:53 {
    reload 5s

    template ANY A test {
        answer "{{ .Name }} 60 IN A www"
        upstream 127.0.0.11:53
    }

    template ANY CNAME test {
        answer  "{{ .Name }} 60 IN CNAME www"
        upstream 127.0.0.11:53
    }

    forward . /etc/resolv.conf
    log
    errors
}
```

I also tried `rewrite name regex \.test\.$ www` which works properly but it misses the `test` domain record. The answer is then.
`dig test.test @127.0.0.1`
```
;; ANSWER SECTION:
www.                    600     IN      A       172.31.0.8
```

BTW `127.0.0.11` (the only record in `/etc/recolv.conf`) is the IP of the internal docker DNS server. I would like to get rid of specifying it in `Corefile` too.

**Comment by chrisohaver** [comment]
For the template solution: 
* `{{ .Name }} 60 IN A www` is invalid because an A record has to be a ipv4 address, not a domain name.
* fully qualify the www in the template (i.e. a dot at the end) e.g. `answer "{{ .Name }} 60 IN CNAME www."`. template MIGHT tolerate the nonfqdn here, but better to be correct and make it fqdn.
* you probably want to match ANY ANY ... and return a CNAME record answer.
* I recommend updating to a recent version of coredns, and removing the `upstream` lines


For the _rewrite_ solution: you'll need to do answer rewrites (See section in the rewrite plugin README). This is automatic in recent versions of coredns, but in very old versions it is required to be explicitly configured.

**Comment by maryo** [comment]
Thank you very much. Both solutions work very well. Now I don't understand how it is possible I could't come up with the solution. I was really trying for some time. It is well described in the docs👼.
