### ISSUE TITLE
CoreDns support Debian 12?

### ISSUE THREAD

**Issue by mwpr34-Manoj** [miekg/coredns#6649]
**What would you like to be added**:
Does the CoreDNS supports Debian 12
**Why is this needed**:
We are upgrading to Debian 12, so making sure the COREDNS supports it.
If no is there a plan to have this impleemeted?

**Comment by jhawkins1** [comment]
To clarify the request....  

Since Debian 12 Distroless is available, as well as, the latest releases of Kubernetes and many of the Kubernetes components and related projects have moved to Debian 12, we would request that coredns move to Debian 12 Distroless.   The benefits:  Alignment of OS to other Kubernetes related Projects;  Reduces fan-out of multiple OSes or different versions of OSes across K8 components; and potential benefits as to being able to obtain OS patches for vulnerabilities where Debian has decided only to fix in latest LTS (Debian 12) release and not earlier releases (ex. Debian 11).

If accepted, we would like ETA and target coredns release for the upgrade.   If we can help with testing, etc.... please let us know.

**Comment by SuperQ** [comment]
CoreDNS should work just fine on Debian 12.

**Comment by jhawkins1** [comment]
@SuperQ , as a follow-up, when will CoreDNS Dockerfile be changed to Debian 12 Distroless?    Or do you need us to do some work for these changes?

**Comment by jhawkins1** [comment]
@SuperQ , digging into some of the existing PRs, it looks like CoreDNS Dockerfile has been updated to Debian 12 in #6416.  So, I guess the question now is when will the PR be merged?
