### ISSUE TITLE
Vulneribilities reported for multiple deplendencies in cordns 

### ISSUE THREAD

**Issue by shivangi24** [miekg/coredns#6737]
### Summary
The Twistlock scan tool reported some and high vulnerability issues for CoreDNS. The latest version of CoreDNS was released in August 2023, and most of these vulnerabilities were introduced after that.

### Details
Adding the twistlock scan report for reference .
[vulnerability_report.xlsx](https://github.com/user-attachments/files/15742711/vulnerability_report.xlsx)

Could you please let me know if the community plans to resolve these CVEs in new version of CoreDNS ?

**Comment by Enrico204** [comment]
Do you have a scenario (with CoreDNS running) which is susceptible to one or more of these issues? Can you provide some clues about them?

**Comment by imuni4fun** [comment]
this is the content of that file for those not using MS Office

|CVE|Score|Pub_Date|Severity|Package|Package Version|Fixed Version|
|---|---|---|---|---|---|---|
|CVE-2024-22189 | 0 | 2024-04-04 | high | github.com/quic-go/quic | v0.37.3 | fixed in 0.42.0 |  
|CVE-2023-44487 | 5.3 | 2023-10-10 | high | golang.org/x/net | v0.12.0 | fixed in 0.17.0 |  
|CVE-2023-44487 | 5.3 | 2023-10-10 | high | google.golang.org/grpc | v1.57.0 | fixed in 1.58.3, 1.57.1, 1.56.3 |  
|CVE-2023-39325 | 7.5 | 2023-10-11 | high | golang.org/x/net/http2 | v0.12.0 | fixed in 0.17.0 |  
|CVE-2024-22189 | 0 | 2024-04-04 | high | github.com/quic-go/quic | v0.37.3 | fixed in 0.42.0 |  
|CVE-2023-44487 | 5.3 | 2023-10-10 | high | golang.org/x/net | v0.12.0 | fixed in 0.17.0 |  
|CVE-2023-44487 | 5.3 | 2023-10-10 | high | google.golang.org/grpc | v1.57.0 | fixed in 1.58.3, 1.57.1, 1.56.3 |  
|CVE-2023-39325 | 7.5 | 2023-10-11 | high | golang.org/x/net/http2 | v0.12.0 | fixed in 0.17.0 |

**Comment by SuperQ** [comment]
Please do not report raw vulnerability scanner results. They are prone to false positives and cause the maintainers toil in verifying. Please verify vulnerability reports and include specific details as to which components are directly exploitable.
