### ISSUE TITLE
error getting ClusterInformation: connection is unauthorized: Unauthorized

### ISSUE THREAD

**Issue by smallemployees** [miekg/coredns#6773]
**What happened**:
error getting ClusterInformation: connection is unauthorized: Unauthorized

**What you expected to happen**:
How to quickly restore the environment and solve problems
**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:

- the version of CoreDNS:
- Corefile:
- logs, if applicable:
- OS (e.g: `cat /etc/os-release`):
- Others:

**Comment by mariuskimmina** [comment]
Sounds like there is an issue with your setup.
These kind of questions are generally better suited for slack (#coredns on https://slack.cncf.io/)
Also please provide some additional information (Where are you running CoreDNS? Where are you seeing this error? etc.) so that people can better help you figure out what's happening.
